version: "3"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer
    #   Maps local port 5432 to port 5432 on the container.
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data